version: '3.8'

services:
  own-back-end:
    container_name: own-back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile    
    networks:
      - own-poli-network
    ports:
      - "9091:8080"

  own-frontend:
    container_name: own-frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - own-back-end
    environment:
      # - API_URL=https://pokeapi.co/api/v2
      - API_URL=http://localhost:9091/api/v2
    networks:
      - own-poli-network
    ports:
      - "9092:80"    

networks:
  own-poli-network:
    driver: bridge
    name: own-poli-network
