version: '3.8'

services:
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile    
    networks:
      - poli-network
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end
    environment:
      # - API_URL=https://pokeapi.co/api/v2
      - API_URL=http://localhost:8080/api/v2
    networks:
      - poli-network
    ports:
      - "8081:80"    

networks:
  poli-network:
    driver: bridge
    name: poli-network